sensor:
  # Note that on the Shelly EM Gen3, channels "A" and "B" are swapped between the chipset and the labels on the device.
  # The nIRQ pin of the ade7953 device seems to be connected to pin 9 (GPIO4)
  # of the ESP-Shelly-C38F.
  - platform: ade7953_i2c
    id: ade7953_id
    irq_pin: GPIO4
    update_interval: ${update_interval}
    use_accumulated_energy_registers: true

    voltage_gain: ${calibration_voltage_gain}
    current_gain_a: ${calibration_current_gain_a}
    current_gain_b: ${calibration_current_gain_b}

    voltage:
      id: voltage
      name: Voltage
    frequency:
      id: frequency
      name: Frequency
    current_b:
      id: current_a
      name: ${ "Current A" if dual_sensors else "Current" }
      accuracy_decimals: 3
    current_a:
      id: current_b
      name: Current B
      accuracy_decimals: 3
    power_factor_b:
      id: power_factor_a
      name: ${ "Power Factor A" if dual_sensors else "Power Factor" }
      filters:
        - multiply: -1
    power_factor_a:
      id: power_factor_b
      name: "Power Factor B"
      filters:
        - multiply: -1
    apparent_power_b:
      id: apparent_power_a
      name: ${ "Apparent Power A" if dual_sensors else "Apparent Power" }
    apparent_power_a:
      id: apparent_power_b
      name: "Apparent Power B"
    active_power_b:
      id: active_power_a
      name: ${ "Power A" if dual_sensors else "Power" }
    active_power_a:
      id: active_power_b
      name: "Power B"
    reactive_power_b:
      id: reactive_power_a
      name: ${ "Reactive Power A" if dual_sensors else "Reactive Power" }
      filters:
        - multiply: -1
    reactive_power_a:
      id: reactive_power_b
      name: "Reactive Power B"
      filters:
        - multiply: -1

  - platform: integration
    id: energy_a
    name: ${ "Energy A" if dual_sensors else "Energy" }
    sensor: active_power_a
    restore: false
    time_unit: h
    icon: mdi:meter-electric
    unit_of_measurement: "kWh"
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  - platform: integration
    id: energy_b
    name: 'Energy B'
    sensor: active_power_b
    restore: false
    time_unit: h
    icon: mdi:meter-electric
    unit_of_measurement: "kWh"
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  - platform: total_daily_energy
    id: daily_energy_consumed_a
    name: ${ "Daily Energy Consumed A" if dual_sensors else "Daily Energy Consumed" }
    power_id: active_power_a
    icon: "mdi:hours-24"
    unit_of_measurement: "kWh"
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  - platform: total_daily_energy
    id: daily_energy_consumed_b
    name: "Daily Energy Consumed B"
    power_id: active_power_b
    icon: "mdi:hours-24"
    unit_of_measurement: "kWh"
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  - platform: combination
    id: active_power_ab
    type: sum
    name: "Power Total"
    sources:
      - source: active_power_a
      - source: active_power_b
    device_class: power
    state_class: measurement

  - platform: combination
    id: energy_ab
    type: sum
    name: "Energy Total"
    sources:
      - source: energy_a
      - source: energy_b
    state_class: total_increasing
    accuracy_decimals: 3

  - platform: combination
    id: daily_energy_consumed_ab
    type: sum
    name: "Daily Energy Consumed Total"
    sources:
      - source: daily_energy_consumed_a
      - source: daily_energy_consumed_b
    state_class: total_increasing
    accuracy_decimals: 3

  - id: !remove ${ "active_power_b" if not dual_sensors else "" }
  - id: !remove ${ "apparent_power_b" if not dual_sensors else "" }
  - id: !remove ${ "current_b" if not dual_sensors else "" }
  - id: !remove ${ "daily_energy_consumed_b" if not dual_sensors else "" }
  - id: !remove ${ "daily_energy_consumed_ab" if not dual_sensors else "" }
  - id: !remove ${ "energy_ab" if not dual_sensors else "" }
  - id: !remove ${ "energy_b" if not dual_sensors else "" }
  - id: !remove ${ "power_ab" if not dual_sensors else "" }
  - id: !remove ${ "power_factor_b" if not dual_sensors else "" }
  - id: !remove ${ "reactive_power_b" if not dual_sensors else "" }
