# MAC address: 38:2C:E5:D5:4D:F2

esphome:
  #name: cb3s-scratch
  #friendly_name: cb3s-scratch
  name: furnace-humidifier-controller
  friendly_name: furnace-humidifier-controller

bk72xx:
  board: cb3s

# Logs are output on the TXD2 pin (Pin 11 - third from the bottom on the right side)
logger:
  level: DEBUG
  baud_rate: 115200
  #hardware_uart: uart1
  # XXX - Logging on uart1 seems to get stuck shortly after boot.

debug:

api:
  encryption:
    key: !secret furnace-humidifier-controller.hass_api_key

ota:
  - platform: esphome
    password: !secret furnace-humidifier-controller.ota_password
    on_begin:
      - valve.close: valve_1
      - logger.log: "Ensuring valve is closed before performing OTA update"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #min_auth_mode: WPA2
  fast_connect: true
  #use_address: "cb3s-scratch.local"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "furnace-humidifer-controlle 4DF2"
    password: !secret furnace-humidifier-controller.ap_password

captive_portal:

network:
  enable_ipv6: true
#  min_ipv6_addr_count: 2

safe_mode:
  reboot_timeout: 10min

time:
  - platform: homeassistant
    id: homeassistant_time

  - platform: sntp
    id: sntp_time
    # timezone: America/Edmonton
    on_time:
      # Every 5 minutes
      - seconds: 0
        minutes: /5
        then:
          - button.press: button_auto_flush

sensor:
  - platform: uptime
    type: seconds
    name: Uptime
    update_interval: 5s

  - platform: internal_temperature
    id: cpu_temperature
    name: "CPU Temperature"

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: diagnostic
    device_class: ""

button:
  - platform: template
    id: button_auto_flush
    name: Auto flush
    on_press:
      - logger.log: "Auto-flush requested."
      - if:
          condition:
            switch.is_on: auto_flush_enabled
          then:
            - logger.log: "Auto-flush enabled; flushing."
            - button.press: button_flush
          else:
            - logger.log: "Auto-flush disabled; not flushing."

  - platform: template
    id: button_flush
    name: Flush
    on_press:
      - logger.log: "Flush: Opening valve_1"
      - valve.open: valve_1
      - logger.log:
          format: "Flush: Delaying %f seconds"
          args: [ "id(flushing_open_duration_id).state" ]
      - delay: !lambda "return 1000 * id(flushing_open_duration_id).state;"
      - logger.log: "Flush: Closing valve_1"
      - valve.close: valve_1

  - platform: restart
    id: button_restart
    name: Restart

  - platform: safe_mode
    id: button_safe_mode
    name: Safe Mode Boot

  - platform: factory_reset
    id: button_factory_reset
    name: Factory reset
    disabled_by_default: true

text_sensor:
  - platform: wifi_info
    ip_address:
      name: Device IP Address
      address_0:
        name: Device IP Address 0
      address_1:
        name: Device IP Address 1
      address_2:
        name: Device IP Address 2
      address_3:
        name: Device IP Address 3
      address_4:
        name: Device IP Address 4
    ssid:
      name: Device Connected SSID
    bssid:
      name: Device Connected BSSID
    mac_address:
      name: Device Mac Wifi Address
    #scan_results:
    #  name: Device Latest Scan Results
    dns_address:
      name: Device DNS Address
    power_save_mode:
      name: Device Wifi Power Save Mode

light:
  - platform: status_led
    name: "Status LED"
    id: status_led_id
    disabled_by_default: true
    entity_category: diagnostic
    pin:
      number: P20
      # The signal is inverted, but I like seeing a status light when the device is powered.
      #inverted: true

binary_sensor:
  - platform: gpio
    name: "Button 1"
    id: button_1
    pin:
      number: P10
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - settle: 10ms
    on_click:
      then:
        - switch.toggle: relay_1

  - platform: gpio
    name: "Button 2"
    id: button_2
    pin:
      number: P11
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - settle: 10ms
    on_click:
      then:
        - switch.toggle: relay_2

  - platform: gpio
    name: "Button 3"
    id: button_3
    pin:
      number: P8
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - settle: 10ms
    on_click:
      then:
        - switch.toggle: relay_3

  - platform: gpio
    name: "Button 4"
    id: button_4
    pin:
      number: P7
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - settle: 10ms
    on_click:
      then:
        - switch.toggle: relay_4

  - platform: gpio
    id: toggle_all_button
    pin:
      number: P9
      inverted: true
      mode:
        input: true
        pullup: true
    #name: "Pair/Toggle All Button"
    # on_click:
    #   then:
    #     - switch.toggle: relay_1
    #     - switch.toggle: relay_2
    #     - switch.toggle: relay_3
    #     - switch.toggle: relay_4
    name: "Flush button"
    filters:
      - settle: 10ms
    on_click:
      then:
        - button.press: button_flush

switch:
  - platform: gpio
    name: "Relay 1"
    id: relay_1
    pin: P24

  - platform: gpio
    name: "Relay 2"
    id: relay_2
    pin: P6

  - platform: gpio
    id: relay_3
    name: "Relay 3"
    pin: P26

  - platform: gpio
    id: relay_4
    name: "Relay 4"
    pin: P14

  - platform: template
    id: auto_flush_enabled
    name: "Automatic flushing"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config

valve:
  - platform: template
    name: "Humidifier drain valve"
    id: valve_1
    lambda: |-
      if (id(relay_1).state) {
        return VALVE_OPEN;
      } else {
        return VALVE_CLOSED;
      }
    open_action:
      - switch.turn_on: relay_1
    close_action:
      - switch.turn_off: relay_1
    stop_action:
      - valve.close: valve_1

number:
  - platform: template
    id: flushing_open_duration_id
    name: "Flushing open duration"
    entity_category: config
    optimistic: true
    min_value: 0
    max_value: 300
    step: 1
    restore_value: True
    initial_value: 60
