substitutions:
  name: "mini"
  friendly_name: "Mini Example"

dashboard_import:
  package_import_url: github://dlitz/esphome-configs-dlitz/mini.yaml@wip

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: "dlitz.mini"
    version: "v0.0.0"
  platformio_options:
    platform_packages:
      - "library-lwip @ https://github.com/dlitz/lwip.git#mdns-big-txt_bdk"
  includes:
    - "<lwip/apps/mdns_priv.h>" # for struct mdns_service, struct mdns_txtdata
    - "<lwip/init.h>"           # for LWIP_VERSION_STRING

bk72xx:
  board: cb3s
  # Flash size: 2MiB
  # CPU Frequency: 120MHz
  framework:
    loglevel: debug
    debug:
      # - lwip
      - mdns
    sdk_silent: auto
    options:
      # LT_LOG_HEAP: 1
      LT_AUTO_DOWNLOAD_REBOOT: 1
      MDNS_TXT_RDATA_SIZE: 384
    # version: "1.9.2"
    # source: "https://github.com/dlitz/libretiny.git#mdns-big-txt"

# external_components:
#   - source:
#       type: git
#       url: https://github.com/dlitz/esphome.git
#       ref: mdns-big-txt
#     components: [libretiny, bk72xx]
#     refresh: always

# Logs are output on the TXD2 pin (Pin 11 - third from the bottom on the right side)
logger:
  level: DEBUG
  baud_rate: 115200

api:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # fast_connect: true

  # use_address: "mini-61b5d1.local"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:

captive_portal:

text_sensor:
  - platform: libretiny
    version:
      name: LibreTiny Version

  - platform: template
    name: "LWIP_VERSION_STRING"
    entity_category: diagnostic
    lambda: |-
      static const std::string s = LWIP_VERSION_STRING;
      return s;

sensor:
  - platform: template
    name: "MDNS_TXT_RDATA_SIZE"
    accuracy_decimals: 0
    entity_category: diagnostic
    lambda: |-
      #ifdef MDNS_TXT_RDATA_SIZE
      return MDNS_TXT_RDATA_SIZE;
      #else
      return {};
      #endif

  - platform: template
    name: "size of mdns_service.txtdata"
    accuracy_decimals: 0
    entity_category: diagnostic
    lambda: |-
      struct mdns_service srv;
      return sizeof(srv.txtdata);

#  - platform: template
#    name: "size of mdns_txtdata.rdata"
#    accuracy_decimals: 0
#    entity_category: diagnostic
#    lambda: |-
#      struct mdns_txtdata txt;
#      return sizeof(txt.rdata);

binary_sensor:
  - platform: template
    name: "LWIP_MDNS_RESPONDER"
    lambda: |-
      #if !defined(LWIP_MDNS_RESPONDER)
      # error LWIP_MDNS_RESPONDER not defined
      #elif LWIP_MDNS_RESPONDER
      return true;
      #else
      return false;
      #endif
