substitutions:
  name: "mini-esp32s3"
  friendly_name: "Mini ESP32S3 Example"

dashboard_import:
  package_import_url: github://dlitz/esphome-configs-dlitz/mini-esp32s3.yaml@wip

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: "dlitz.mini-esp32s3"
    version: "v0.0.0"

esp32:
  #board: esp32s3box
  #board: adafruit_feather_esp32s3
  variant: esp32s3
  flash_size: 4MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

# Logs are output on the TXD2 pin (Pin 11 - third from the bottom on the right side)
logger:
  level: DEBUG
  baud_rate: 115200

api:

ota:
  platform: esphome

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:

captive_portal:

