# Shelly EM Gen3
# Model number: S3EM-002CXCEU50
# PCB markings: "EM Gen3_v0.1.3", "B2519"
# SoC: ESP-Shelly-C38F (similar to ESP32-C3)
# CPU: ESP32-C3 (QFN32) (revision v0.4)
# Features: Wi-Fi, BT 5 (LE), Single Core, 160MHz, Embedded Flash 8MB (GD)
# Crystal frequency:  40MHz
# References:
# - https://devices.esphome.io/devices/shelly-em-gen3/
# - https://community.home-assistant.io/t/shelly-em-gen3-solved/944171
# - https://kb.shelly.cloud/knowledge-base/shelly-em-gen3
#
# GPIOs:
#   GPIO0 - Dry-contact relay (normally open)
#   GPIO1 - Pushbutton
#   GPIO3 - ADC for NTC temperature sensor
#   GPIO4 - ADE7953 IRQ pin (active low)
#   GPIO5 - ADE7953 RESET pin (active low)
#   GPIO6 - I2C SCL
#   GPIO7 - I2C SDA
#   GPIO9 - Status LED (active low)
#   GPIO18 - Pin 1 of 7-pin header
#   GPIO20 - UART receive (U0RXD)
#   GPIO21 - UART transmit (U0TXD)
#
# I2C devices:
#  0x38 - ADE7953 Power Sensor
#  0x51 - AiP8563 Battery-backed real-time clock (not currently supported by ESPHome)

# Outputting LOW on GPIO5 seems to produce HIGH on GPIO4, and vice versa

substitutions:
  # Set dual_sensors to false to remove the "B" and "Total" sensors
  dual_sensors: true

  # How often to update the power meter.
  update_interval: 20s

  # Calibrated on US-style 120V power with 50A current transformers.
  # You may need to calibrate this yourself if the numbers are inaccurate.
  calibration_voltage_gain: 0x32c78f    # Calibrated on device E4:B0:63:D4:3E:00
  calibration_current_gain_a: 0x490bb5  # Calibrated on device E4:B0:63:D4:3E:00
  calibration_current_gain_b: 0x498c15  # Calibrated on device E4:B0:63:D4:3E:00

  # GPIOs for this type of device
  shelly_button_gpio_number: GPIO1
  shelly_header_gpio_number: GPIO18
  shelly_ntc_temperature_pin: GPIO3

dashboard_import:
  package_import_url: github://dlitz/esphome-configs-dlitz/shelly-em-gen3.yaml@${git_branch}

packages:
  - !include common/esp-shelly-c38f.yaml
  - !include common/cpu-temperature.yaml
  - !include common/factory-reset.yaml
  - !include common/flash-write-interval.yaml
  - !include common/git-branch.yaml
  - !include common/ota.yaml
  - !include common/ota-update-password.yaml
  - !include common/restart.yaml
  - !include common/safe-mode.yaml
  - !include common/shelly-button.yaml
  - !include common/shelly-header-gpio.yaml
  - !include common/shelly-ntc-temperature.yaml
  - !include common/time.yaml
  - !include common/uptime-info.yaml
  - !include common/wifi-info.yaml
  - !include include/shelly-em-gen3/base-sensors.yaml

esphome:
  name: "shelly-em-gen3"
  friendly_name: "Shelly EM Gen3"
  comment: "Shelly EM Gen3 - Smart wifi and bluetooth energy meter with dual current transformers"
  name_add_mac_suffix: true
  project:
    name: "dlitz.shelly-em-gen3"
    version: "v0.0.0"
  min_version: 2025.11.3    # for ade7953 bugfix #12180

# Enable logging
logger:
  level: DEBUG
  hardware_uart: uart0

# debug:

# Enable Home Assistant API with dynamic key
api:
  encryption:

wifi:
  # ssid: !secret wifi_ssid
  # password: !secret wifi_password
  # fast_connect: true
  enable_btm: true
  enable_rrm: true
  min_auth_mode: WPA2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret default_ap_password

captive_portal:

network:
  enable_ipv6: true

i2c:
  scl: GPIO6
  sda: GPIO7
  scan: true

improv_serial:

esp32_improv:
  authorizer: shelly_button_id

# esp32_ble_tracker:
#   scan_parameters:
#     active: false
#
# bluetooth_proxy:
#   active: false

light:
  - platform: status_led
    name: "Status LED"
    id: status_led_id
    disabled_by_default: true
    entity_category: diagnostic
    pin:
      number: GPIO9
      inverted: true
      ignore_strapping_warning: true

switch:
  # Dry-contact relay - normally open
  - platform: gpio
    name: Relay
    id: relay
    pin: GPIO0

