# Shelly EM Gen3
# PCB markings: "EM Gen3_v0.1.3", "B2519"
# CPU: ESP32-Shelly (ESP32-C3)
# Ref: https://community.home-assistant.io/t/shelly-em-gen3-solved/944171
#
# GPIOs:
#   GPIO0 - Dry-contact relay (normally open)
#   GPIO1 - Pushbutton
#   GPIO3 - ADC for NTC temperature probe
#   GPIO6 - I2C SCL
#   GPIO7 - I2C SDA
#   GPIO9 - Status LED (active low)
#   GPIO18 - Pin 7 of 7-pin header
#
# I2C devices:
#  0x38 - ADE7953 Power Sensor
#  0x51 - AiP8563 Time Source (battery-backed RTC; note that the Shelly device doesn't have a battery)

# Outputting LOW on GPIO5 seems to produce HIGH on GPIO4, and vice versa

substitutions:
  calibration_voltage_gain: 0x32c78f    # Calibrated on device E4:B0:63:D4:3E:00
  calibration_current_gain_a: 0x490bb5  # Calibrated on device E4:B0:63:D4:3E:00
  calibration_current_gain_b: 0x498c15  # Calibrated on device E4:B0:63:D4:3E:00
  device_name: "Shelly EM Gen3"
  dual_sensors: true
  shelly_button_gpio_number: GPIO1
  shelly_header_gpio_number: GPIO18
  shelly_ntc_temperature_pin: GPIO3
  update_interval: 5s

dashboard_import:
  package_import_url: github://dlitz/esphome-configs-dlitz/shelly-em-gen3.yaml@wip

packages:
  - !include common/esp-shelly-c38f.yaml
  - !include common/cpu-temperature.yaml
  - !include common/factory-reset.yaml
  - !include common/ota.yaml
  - !include common/ota-update-password.yaml
  - !include common/restart.yaml
  - !include common/safe-mode.yaml
  - !include common/shelly-button.yaml
  - !include common/shelly-header-gpio.yaml
  - !include common/shelly-ntc-temperature.yaml
  - !include common/time.yaml
  - !include common/uptime-info.yaml
  - !include common/wifi-info.yaml

esphome:
  name: "shelly-em-gen3"
  friendly_name: "Shelly EM Gen3"
  comment: "Shelly EM Gen3 - Smart wifi and bluetooth energy meter with dual current transformers"
  name_add_mac_suffix: true
  project:
    name: "dlitz.shelly-em-gen3"
    version: "v0.0.0"
  min_version: 2025.11.3    # for ade7953 bugfix #12180

# Enable logging
logger:
  level: DEBUG
  hardware_uart: uart0

# Enable Home Assistant API with dynamic key
api:
  encryption:

wifi:
  enable_btm: true
  enable_rrm: true
  min_auth_mode: WPA2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret fallback_ap_password

captive_portal:

network:
  enable_ipv6: true
  # min_ipv6_addr_count: 2

i2c:
  scl: GPIO6
  sda: GPIO7
  scan: true

# esp32_ble_tracker:
#   scan_parameters:
#     active: false
#
# bluetooth_proxy:
#   active: false

light:
  - platform: status_led
    name: "Status LED"
    id: status_led_id
    disabled_by_default: true
    entity_category: diagnostic
    pin:
      number: GPIO9
      inverted: true
      ignore_strapping_warning: true

switch:
  # Dry-contact relay - normally open
  - platform: gpio
    name: Relay
    id: relay_id
    pin: GPIO0

sensor:
  # Note that on the Shelly EM Gen3, channels "A" and "B" are swapped between the chipset and the labels on the device.
  # Also, I think this device does not need/have an irq_pin.
  - platform: ade7953_i2c
    id: ade7953_id
    update_interval: ${update_interval}
    use_accumulated_energy_registers: true

    voltage_gain: ${calibration_voltage_gain}
    current_gain_a: ${calibration_current_gain_a}
    current_gain_b: ${calibration_current_gain_b}

    voltage:
      id: line_voltage
      name: Voltage
    frequency:
      id: line_frequency
      name: Frequency
    current_b:
      id: current_a
      name: Current A
      accuracy_decimals: 3
    current_a:
      id: current_b
      name: Current B
      accuracy_decimals: 3
      disabled_by_default: ${ not dual_sensors }
    power_factor_b:
      id: power_factor_a
      name: "Power Factor A"
      filters:
        - multiply: -1
    power_factor_a:
      id: power_factor_b
      name: "Power Factor B"
      filters:
        - multiply: -1
      disabled_by_default: ${ not dual_sensors }
    apparent_power_b:
      id: apparent_power_a
      name: "Apparent Power A"
    apparent_power_a:
      id: apparent_power_b
      name: "Apparent Power B"
      disabled_by_default: ${ not dual_sensors }
    active_power_b:
      id: active_power_a
      name: "Power A"
    active_power_a:
      id: active_power_b
      name: "Power B"
      disabled_by_default: ${ not dual_sensors }
    reactive_power_b:
      id: reactive_power_a
      name: "Reactive Power A"
      filters:
        - multiply: -1
    reactive_power_a:
      id: reactive_power_b
      name: "Reactive Power B"
      filters:
        - multiply: -1
      disabled_by_default: ${ not dual_sensors }

  - platform: integration
    id: energy_a
    name: 'Energy A'
    sensor: active_power_a
    restore: false
    time_unit: h
    icon: mdi:meter-electric
    unit_of_measurement: "kWh"
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  - platform: integration
    id: energy_b
    name: 'Energy B'
    sensor: active_power_b
    restore: false
    time_unit: h
    icon: mdi:meter-electric
    unit_of_measurement: "kWh"
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
    disabled_by_default: ${ not dual_sensors }

  - platform: total_daily_energy
    id: total_daily_energy_a
    name: "Total Daily Energy A"
    power_id: active_power_a
    icon: "mdi:hours-24"
    unit_of_measurement: "kWh"
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  - platform: total_daily_energy
    id: total_daily_energy_b
    name: "Total Daily Energy B"
    power_id: active_power_b
    icon: "mdi:hours-24"
    unit_of_measurement: "kWh"
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
    disabled_by_default: ${ not dual_sensors }

  - platform: combination
    id: power_ab
    type: sum
    name: "Power A+B"
    sources:
      - source: active_power_a
      - source: active_power_b
    device_class: power
    state_class: measurement
    disabled_by_default: ${ not dual_sensors }

  - platform: combination
    id: energy_ab
    type: sum
    name: "Energy A+B"
    sources:
      - source: energy_a
      - source: energy_b
    state_class: total_increasing
    accuracy_decimals: 3
    disabled_by_default: ${ not dual_sensors }

  - platform: combination
    id: total_daily_energy_ab
    type: sum
    name: "Total Daily Energy A+B"
    sources:
      - source: total_daily_energy_a
      - source: total_daily_energy_b
    state_class: total_increasing
    accuracy_decimals: 3
    disabled_by_default: ${ not dual_sensors }
