# Shelly EM Gen3
# PCB markings: "EM Gen3_v0.1.3", "B2519"
# CPU: ESP32-Shelly (ESP32-C3)
# Ref: https://community.home-assistant.io/t/shelly-em-gen3-solved/944171
#
# GPIOs:
#   GPIO0 - Dry-contact relay (normally open)
#   GPIO1 - Pushbutton
#   GPIO3 - ADC for NTC temperature probe
#   GPIO6 - I2C SCL
#   GPIO7 - I2C SDA
#   GPIO9 - Status LED (active low)
#   GPIO18 - Pin 7 of 7-pin header
#
# I2C devices:
#  0x38 - ADE7953 Power Sensor
#  0x51 - AiP8563 Time Source (battery-backed RTC)

# Outputting LOW on GPIO5 seems to produce HIGH on GPIO4, and vice versa

substitutions:
  name: "shelly-em-gen3"
  friendly_name: "Shelly EM Gen3"
  room: ""
  device_description: "Smart wifi and bluetooth energy meter with current transformer"
  project_name: "dlitz.shelly-em-gen3"
  project_version: "v0.0.0"
  sensor_update_interval: "10s"
  wifi_fast_connect: "false"
  update_interval: 5s
  calibration_voltage_gain: 0x32c78f    # Calibrated on device E4:B0:63:D4:3E:00
  calibration_current_gain_a: 0x490bb5  # Calibrated on device E4:B0:63:D4:3E:00
  calibration_current_gain_b: 0x498c15  # Calibrated on device E4:B0:63:D4:3E:00
  ota_password: ""
  ota_update_password: "false"
  ota_new_password: ""

dashboard_import:
  package_import_url: github://dlitz/esphome-configs-dlitz/shelly-em-gen3.yaml@wip

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: "${device_description}"
  area: "${room}"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"
  on_boot:
    - lambda: |-
        #ifdef USE_OTA_PASSWORD
        const bool ota_update_password = (${ota_update_password});
        const std::string ota_new_password = "${ota_new_password}";
        if (ota_update_password) {
          if (ota_new_password.empty()) {
            ESP_LOGI("ota_update_password", "Setting blank OTA password");
          } else {
            ESP_LOGI("ota_update_password", "Setting new OTA password");
          }
          id(ota_id).set_auth_password(ota_new_password);
        } else {
          ESP_LOGI("ota_update_password", "No new OTA password");
        }
        #else
        #  error "cannot set new OTA password - not compiled with OTA support (hint: set a dummy ota_password)"
        #endif
  min_version: 2025.11.3    # for ade7953 bugfix #12180

esp32:
  variant: esp32c3
  flash_size: 8MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"  # TLS1.3 support isn't enabled by default in IDF 5.4.2
      CONFIG_MBEDTLS_DEFAULT_CERTIFICATE_BUNDLE: CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_DEFAULT_CMN
      # CONFIG_LWIP_NETIF_LOOPBACK: "n"     # Apparently there's a bug causing the ICMPv6 Router Solicitation to go out over the loopback interface rather than wifi

# Enable logging
logger:
  level: DEBUG
  hardware_uart: uart0

# Enable Home Assistant API with dynamic key
api:
  encryption:

ota:
  - platform: esphome
    id: ota_id
    password: "${ota_password or ota_new_password}"

wifi:
  fast_connect: "${wifi_fast_connect}"
  enable_btm: true
  enable_rrm: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret wifi_fallback_ap_password

captive_portal:

network:
  enable_ipv6: true
  # min_ipv6_addr_count: 2

safe_mode:
  reboot_timeout: 10min

i2c:
  scl: GPIO6
  sda: GPIO7
  scan: true

esp32_ble_tracker:
  scan_parameters:
    active: false

bluetooth_proxy:
  active: false

time:
  - platform: homeassistant
    id: current_time

light:
  - platform: status_led
    name: "Status LED"
    id: status_led_id
    disabled_by_default: true
    entity_category: diagnostic
    pin:
      number: GPIO9
      inverted: true
      ignore_strapping_warning: true

button:
  - platform: restart
    id: button_restart
    name: Restart

  - platform: safe_mode
    id: button_safe_mode
    name: Safe Mode Boot

  - platform: factory_reset
    id: button_factory_reset
    name: Factory Reset
    disabled_by_default: true

binary_sensor:
  - platform: gpio
    name: "Button"
    id: button_id
    entity_category: diagnostic
    pin:
      number: GPIO1
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - settle: 10ms
    on_multi_click:
      - timing:
        - ON for 5s to 10s
        then:
          - button.press: button_safe_mode
      - timing:
        - ON for at least 10s
        then:
          - button.press: button_factory_reset

  - platform: gpio
    id: gpio18_pin_id
    name: "GPIO Pin"
    entity_category: diagnostic
    disabled_by_default: true
    pin:
      number: GPIO18
      inverted: true
      mode:
        input: true
        pullup: true

switch:
  # Dry-contact relay - normally open
  - platform: gpio
    name: Relay
    id: relay_id
    pin: GPIO0

sensor:
  - platform: uptime
    id: uptime_seconds
    name: Uptime
    type: seconds
    disabled_by_default: true

  - platform: uptime
    id: last_reboot
    name: Last Reboot
    type: timestamp

  - platform: internal_temperature
    id: cpu_temperature
    name: "CPU Temperature"

  - platform: ntc
    id: ntc_temperature
    name: "NTC Temperature"
    # entity_category: diagnostic
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    sensor: temp_resistance_reading
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: adc
    id: temp_analog_reading
    pin: GPIO3
    attenuation: 12db

  # Note that on the Shelly EM Gen3, channels "A" and "B" are swapped between the chipset and the labels on the device.
  - platform: ade7953_i2c
    #irq_pin: GPIO1      # TODO - what value goes here?
    update_interval: "${update_interval}"
    use_accumulated_energy_registers: true

    voltage_gain: ${calibration_voltage_gain}
    current_gain_a: ${calibration_current_gain_a}
    current_gain_b: ${calibration_current_gain_b}

    voltage:
      id: line_voltage
      name: Voltage
    frequency:
      id: line_frequency
      name: Frequency
    current_b:
      id: current_a
      name: Current A
      accuracy_decimals: 3
    current_a:
      id: current_b
      name: Current B
      accuracy_decimals: 3
    power_factor_b:
      id: power_factor_a
      name: "Power Factor A"
      filters:
        - multiply: -1
    power_factor_a:
      id: power_factor_b
      name: "Power Factor B"
      filters:
        - multiply: -1
    apparent_power_b:
      id: apparent_power_a
      name: "Apparent Power A"
    apparent_power_a:
      id: apparent_power_b
      name: "Apparent Power B"
    active_power_b:
      id: active_power_a
      name: "Power A"
    active_power_a:
      id: active_power_b
      name: "Power B"
    reactive_power_b:
      id: reactive_power_a
      name: "Reactive Power A"
      filters:
        - multiply: -1
    reactive_power_a:
      id: reactive_power_b
      name: "Reactive Power B"
      filters:
        - multiply: -1

  - platform: integration
    id: energy_a
    name: 'Energy A'
    sensor: active_power_a
    restore: false
    time_unit: h
    icon: mdi:meter-electric
    unit_of_measurement: "kWh"
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  - platform: integration
    id: energy_b
    name: 'Energy B'
    sensor: active_power_b
    restore: false
    time_unit: h
    icon: mdi:meter-electric
    unit_of_measurement: "kWh"
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  - platform: total_daily_energy
    id: total_daily_energy_a
    name: "Total Daily Energy A"
    power_id: active_power_a
    icon: "mdi:hours-24"
    unit_of_measurement: "kWh"
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  - platform: total_daily_energy
    id: total_daily_energy_b
    name: "Total Daily Energy B"
    power_id: active_power_b
    icon: "mdi:hours-24"
    unit_of_measurement: "kWh"
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  - platform: combination
    type: sum
    name: "Power A+B"
    sources:
      - source: active_power_a
      - source: active_power_b
    device_class: power
    state_class: measurement

  - platform: combination
    type: sum
    name: "Energy A+B"
    sources:
      - source: energy_a
      - source: energy_b
    state_class: total_increasing
    accuracy_decimals: 3

  - platform: combination
    type: sum
    name: "Total Daily Energy A+B"
    sources:
      - source: total_daily_energy_a
      - source: total_daily_energy_b
    state_class: total_increasing
    accuracy_decimals: 3

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s

  - platform: copy # Reports the WiFi signal strength in %
    id: wifi_signal_percent
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: diagnostic
    device_class: ""

text_sensor:
  - platform: wifi_info
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
