packages:
  api: !include api.yaml
  captive_portal: !include captive_portal.yaml
  cpu_temperature: !include cpu_temperature.yaml
  factory_reset: !include factory_reset.yaml
  network: !include network.yaml
  ota: !include ota.yaml
  time: !include time.yaml
  wifi: !include wifi.yaml
  wifi_info: !include wifi_info.yaml
