# Common options for the ESP-Shelly-C38F SoC

packages:
  - !include esp32c6.yaml

esphome:
  platformio_options:
    board_build.flash_mode: dio

esp32:
  variant: esp32c6
  # cpu_frequency: 240MHz
  flash_size: 8MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"  # TLS1.3 support still isn't enabled by default in IDF 5.5.2
      # CONFIG_MBEDTLS_DEFAULT_CERTIFICATE_BUNDLE: CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_DEFAULT_CMN
      # CONFIG_LWIP_NETIF_LOOPBACK: "n"     # Apparently there's a bug causing the ICMPv6 Router Solicitation to go out over the loopback interface rather than wifi
