substitutions:
  # shelly_ntc_temperature_pin: GPIO3

sensor:
  - platform: ntc
    id: ntc_temperature
    name: "NTC Temperature"
    entity_category: diagnostic
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    sensor: temp_resistance_reading
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: adc
    id: temp_analog_reading
    pin: ${shelly_ntc_temperature_pin}
    attenuation: 12db

